### ISSUE TITLE
Crash if not Full

### ISSUE THREAD

**Issue by Altamash347** [LuciferVerma/Bedwars#3]
Server is always crashing is an Arena does not have the Maximum amount of players

e.g: In a 4v4v4v4 Arena, So if only 4 players have joinned in a 4v4v4v4 map, It crashes, If 16 players join in a 4v4v4v4 map, It works. Please fix it

**Comment by LuciferVerma** [comment]
Each player have to selected the team.
And this is not happening with me.

**Comment by Altamash347** [comment]
Ok Its fixed automatically
