### ISSUE TITLE
Atleast fix this issue

### ISSUE THREAD

**Issue by Altamash347** [LuciferVerma/Bedwars#5]
Players can break their own beds

Fix it and I will be fine.

**Comment by Altamash347** [comment]
and please dont forget to update the plugin If a new version of Pmmp will release and will break the plugin

**Comment by LuciferVerma** [comment]
Sorry I'm not facing that problem. I can't break my own bed it clearly say that you can't break your own bed.

**Comment by LuciferVerma** [comment]
And I will be update api and some other stuff. Maybe I'll fix everything but I need time. I don't want people who ping me everyday when you will fix it. I have other projects too. Sorry I'll fix everything but not rn.

**Comment by Altamash347** [comment]
ok thanks but i can break it. I will send you a demo vid later in this issue

**Comment by Hoangviphb999** [comment]
Im adding the join command into this Bedwars GUI plugin :)

**Comment by Hoangviphb999** [comment]
And it worked

**Comment by Hoangviphb999** [comment]
Just taking and the old Bedwars Dev-8 by boi and copy and paste the into the game

**Comment by Altamash347** [comment]
Great but now im gonna record a vid and will attach here to show you my issue

**Comment by LuciferVerma** [comment]
You sure config it correctly?

**Comment by Altamash347** [comment]
Yes
Did it correctly but when I break my own Bed, Im like never gonna loose, If I break my own bed, then if I die, it respawns me back and I never loose.

**Comment by Altamash347** [comment]
and I cant cover the backside of the bed

**Comment by Altamash347** [comment]
![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/66252903/94713879-d039e480-0364-11eb-9ddd-450e8e272ed4.gif)
![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/66252903/94713986-ee9fe000-0364-11eb-9227-f3ebf6fef75b.gif)

**Comment by Altamash347** [comment]
@LuciferVerma

**Comment by Altamash347** [comment]
OK I got it, I was not setting my bed correctly, I didnt knew the meaning of Bed 1 and Bed 2. now I figured it out.
